# Generated by Django 3.2.7 on 2021-12-29 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='available',
            new_name='moderated',
        ),
    ]
